Transcom/Controllers/TranscriptController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.ExtendedProperties;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Transcom.Models;
using SubtitlesParser;
using Newtonsoft.Json.Linq;

namespace Transcom.Controllers
{
    public class TranscriptController : Controller
    {



        [HttpPost]
        public async Task<IActionResult> Index(string urlName)
        {
            if (string.IsNullOrWhiteSpace(urlName))
            {
                ModelState.AddModelError("urlName", "Recording URL is required.");
                return View();
            }
            string title = "Transcom";
            try
            {              
                List<string> sentences = new List<string>();
                string[] s = urlName.Split('/');
                string videoId = s.Last();
                string token = "";
                string textTrackUrl = "https://euno-1.api.microsoftstream.com/api/videos/" + videoId + "/texttracks?api-version=1.4-private";
                string titleUrl = "https://euno-1.api.microsoftstream.com/api/videos/" + videoId + "?$expand=creator,tokens,status,liveEvent,extensions&api-version=1.4-private";

                string vttUrl = "";

                HttpResponseMessage urlResponse = await GetHttpResponse(textTrackUrl, token);
                if (urlResponse.IsSuccessStatusCode)
                {
                    var textTracksResponseString = await urlResponse.Content.ReadAsStringAsync();
                    TextTracksResponse textTracksResponse = JsonConvert.DeserializeObject<TextTracksResponse>(textTracksResponseString);
                    vttUrl = textTracksResponse?.value?[0].url;
                }
                else
                {
                    ModelState.AddModelError("urlName", " Video not found in URL.");
                    return View();
                }


                HttpResponseMessage titleResponse = await GetHttpResponse(titleUrl, token);
                if (titleResponse.IsSuccessStatusCode)
                {
                    var textTracksResponseString = await titleResponse.Content.ReadAsStringAsync();
                    var responseJObject = JObject.Parse(textTracksResponseString);
                    title = (string)responseJObject["name"];
                }


                sentences = ExtractVttContent(token, vttUrl);

                //Create Word file
                string fileName = title + ".docx";
                string path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, fileName);
                CreateWordprocessingDocument(path, title, sentences);
                TempData["Path"] = "";
                TempData["Path"] = path;
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("file", string.Format("Can you please close {0} file.", title));
                return View();
            }

            return View();
        }

        private async Task<HttpResponseMessage> GetHttpResponse(string url, string token)
        {
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Add("authorization", token);
                HttpResponseMessage response = await client.GetAsync(url);

                return response;
            }
        }

        private static List<string> ExtractVttContent(string token, string vttUrl)
        {
            List<string> sentences = new List<string>();
            using (var client = new WebClient())
            {

                client.Headers.Clear();

                client.Headers.Add("authorization", token);
                var content = client.DownloadData(vttUrl);
                using (var stream = new MemoryStream(content))
                {
                    string fileName = "file.txt";
                    string path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, fileName);
                    FileStream file = new FileStream(path, FileMode.Create, FileAccess.Write);
                    stream.WriteTo(file);
                    file.Close();

                    SubtitlesParser.Classes.Parsers.SubParser parser = new SubtitlesParser.Classes.Parsers.SubParser();

                    using (var fileStream = new FileStream(path, FileMode.Open, FileAccess.Read))
                    {
                        try
                        {
                            var mostLikelyFormat = parser.GetMostLikelyFormat(fileStream.Name);
                            var items = parser.ParseStream(fileStream, Encoding.UTF8, mostLikelyFormat);

                            string sentence = " ";
                            foreach (var item in items)
                            {
                                foreach (var line in item.Lines)
                                {
                                    foreach (var word in line.ToCharArray())
                                    {
                                        sentence = sentence + word;

                                        if (word.Equals('.') || word.Equals('?'))
                                        {
                                            sentences.Add(sentence);
                                            sentence = string.Empty;
                                        }
                                    }
                                    sentence = sentence + " ";
                                }
                            }
                            //Remove small talks from trans script sentences
                            RemoveSmallTalks(sentences);
                        }
                        catch (Exception ex)
                        {

                        }
                    }
                }
            }
            return sentences;
        }

        private static void RemoveSmallTalks(List<string> sentences)
        {
            List<string> smallTalks = new List<string>();
            foreach (string sm in SmallTalkDictionary.smallTalks)
            {
                smallTalks.AddRange(sentences.FindAll(s => s.ToLower().Contains(sm.ToLower())));
            }
            sentences?.RemoveAll(st => smallTalks.Contains(st));
        }

        [HttpGet]
        public async Task<IActionResult> Download(string path)
        {
            var memory = new MemoryStream();
            using (var stream = new FileStream(path, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;
            var ext = Path.GetExtension(path).ToLowerInvariant();
            return File(memory, GetMimeTypes()[ext], Path.GetFileName(path));
        }

        private Dictionary<string, string> GetMimeTypes()
        {
            return new Dictionary<string, string>
        {
            {".txt", "text/plain"},
            {".pdf", "application/pdf"},
            {".doc", "application/vnd.ms-word"},
            {".docx", "application/vnd.ms-word"},
            {".png", "image/png"},
            {".jpg", "image/jpeg"}
        };
        }

        public void CreateWordprocessingDocument(string filepath, string title, List<string> conversation)
        {
            // Create a document by supplying the filepath. 
            using (WordprocessingDocument wordDocument =
                WordprocessingDocument.Create(filepath, WordprocessingDocumentType.Document))
            {
                // Add a main document part. 
                MainDocumentPart mainPart = wordDocument.AddMainDocumentPart();
                AddSettingsToMainDocumentPart(mainPart);

                // Create the document structure and add some text.
                Document doc = new Document();

                HeaderPart headerPart = mainPart.AddNewPart<HeaderPart>("rId7");
                GenerateHeader(headerPart);

                Body body = new Body();
                // 1 paragrafo
                Paragraph para = new Paragraph();

                ParagraphProperties paragraphProperties1 = new ParagraphProperties();
                ParagraphStyleId paragraphStyleId1 = new ParagraphStyleId() { Val = "Bold" };
                Justification justification1 = new Justification() { Val = JustificationValues.Center };
                ParagraphMarkRunProperties paragraphMarkRunProperties1 = new ParagraphMarkRunProperties();

                paragraphProperties1.Append(paragraphStyleId1);
                //paragraphProperties1.Append(fontSize1);
                paragraphProperties1.Append(justification1);
                paragraphProperties1.Append(paragraphMarkRunProperties1);

                Run run = new Run();
                RunProperties runProperties1 = new RunProperties(new FontSize() { Val = "50" }, new Bold() { Val = OnOffValue.FromBoolean(true) });

                Text text = new Text() { Text = title };

                // siga a ordem 
                run.Append(runProperties1);
                run.Append(text);
                para.Append(paragraphProperties1);
                para.Append(run);
                body.Append(para);
                //Paragraph titlePara = CreateParagraph( title, JustificationValues.Center);
                //body.Append(titlePara);

                // "Here are the discussed points:" Paragraph

Transcom/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Transcom</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>

    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-inverse navbar-light  border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Transcript" asp-action="Index">Transcom</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex  navbar-right">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item navbar-right">
                            <a  asp-area="" asp-controller="Transcript" asp-action="Index">Home</a>
                        </li>

                    </ul>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                    <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>                   
                </ul>
            </div>
        </nav>
   
    </header>

  
    <div class="container">
        <main role="main" class="pb-3" style="padding:2%">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Transcom
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>